packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@embedded-postgres/linux-x64": true
  esbuild: true
  lightningcss: true
  sharp: true
  unrs-resolver: true
  workerd: true
  msw: false

catalog:
  typescript: 6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0-rc.0
  vite-plus: 1.0.0-rc.0

overrides:
  vite@*: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
