// `pnpm documents:build`: parses every Common Paper template into a typed
// module in generated/, so the app renders from data and never parses
// markdown at runtime. Also runs on install (`prepare`).
import { mkdirSync, rmSync, writeFileSync } from "node:fs"

import {
  COVER_PAGE_FILE,
  readCatalog,
  readTemplate,
  templateId,
} from "../src/parse/catalog.ts"
import { parseCoverPage, parseStandardTerms } from "../src/parse/parse.ts"

const out = new URL("../generated/", import.meta.url)
rmSync(out, { recursive: true, force: true })
mkdirSync(out)

const catalog = readCatalog()

// The catalog too, keyed by template id, so a definition reads its name and
// description with literal keys and no lookup can miss.
writeFileSync(
  new URL("catalog.ts", out),
  [
    "// Generated by `pnpm documents:build` from catalog.json. Do not edit.",
    'import type { CatalogEntry } from "../src/parse/catalog.ts"',
    "",
    `const catalog = ${JSON.stringify(
      Object.fromEntries(
        catalog.map((entry) => [templateId(entry.filename), entry])
      )
    )} satisfies Record<string, CatalogEntry>`,
    "",
    "export default catalog",
    "",
  ].join("\n")
)

for (const { filename } of catalog) {
  const markdown = readTemplate(filename)
  const [type, tree] =
    filename === COVER_PAGE_FILE
      ? ["CoverPage", parseCoverPage(markdown)]
      : ["StandardTerms", parseStandardTerms(markdown)]

  // A typed module, not JSON: the type annotation checks the tree against the
  // schema's type at compile time, with no cast and no parse at runtime.
  writeFileSync(
    new URL(`${templateId(filename)}.ts`, out),
    [
      `// Generated by \`pnpm documents:build\` from templates/${filename}. Do not edit.`,
      `import type { ${type} } from "../src/parse/schema.ts"`,
      "",
      `const template: ${type} = ${JSON.stringify(tree)}`,
      "",
      "export default template",
      "",
    ].join("\n")
  )
}
